### ISSUE TITLE
ambitools2supercollider.sh: error in compiling supercollider plugins

### ISSUE THREAD

**Issue by LFSaw** [sekisushai/ambitools#1]
Hello,

I found the ambitools2suppercollider shell script but was unable to compile the files due to several (hundred) errors. I pasted the error report here:

https://pastebin.com/Z2vhTf7D

Any help much appreciated.

**Comment by sekisushai** [comment]
Hello,
Sorry for my late answer, I didn't notice the issue...
I guess the errors comes because there is no specified name for the UGen:
In your pasted report, at line 33 there is no name specified. Thus, faust2sc script makes an error from that I guess.
I've updated the script with automatic naming convention according to HOAUgens nomenclature chosen by @florian-grond. The compilation should work now.
